name: Build DeskAI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install dependencies
        run: npm install
        
      - name: Build frontend
        run: npm run build
        
      - name: Build Tauri app
        run: npm run tauri build
        
      - name: Upload MSI artifact
        uses: actions/upload-artifact@v4
        with:
          name: deskai-msi
          path: src-tauri/target/release/bundle/msi/*.msi
          
      - name: Upload NSIS artifact
        uses: actions/upload-artifact@v4
        with:
          name: deskai-nsis
          path: src-tauri/target/release/bundle/nsis/*.exe

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev \
            libappindicator3-dev \
            librsvg2-dev \
            patchelf
        
      - name: Install dependencies
        run: npm install
        
      - name: Build frontend
        run: npm run build
        
      - name: Build Tauri app
        run: npm run tauri build
        
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v4
        with:
          name: deskai-appimage
          path: src-tauri/target/release/bundle/appimage/*.AppImage
